---
title: panel
author: Kenji MIYAZAKI
date: '2017-08-03'
slug: panel
categories:
  - R
tags:
  - R Markdown
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## library
```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(knitr)
library(broom)
library(AER)
library(plm)
library(texreg)
```

## data
```{r}
data("Fatalities")
df <- Fatalities %>% 
  mutate(frate = 10000 * fatal/pop,
         vmiles = miles/1000,
         punish= factor(jail == "yes" | service == "yes", labels = c("no", "yes")),
         drinkagec=relevel(
           cut(drinkage, breaks =18:22, include.lowest = TRUE, right = FALSE), ref = 4))
head(df) %>% kable()
```

## for comparability with Stata we use HC1 below
### p. 351, Eq. (10.2)
```{r}
fm1982 <- df %>% filter(year=="1982") %>% lm(frate ~beertax, data = .)
coeftest(fm1982, vcov = vcovHC(fm1982, type = "HC1")) %>% tidy() %>% kable()
```

### p. 351, Eq. (10.2)
```{r}
fm1988 <- df %>% filter(year=="1988") %>% lm(frate ~beertax, data = .)
coeftest(fm1988, vcov = vcovHC(fm1988,type = "HC1")) %>% tidy() %>% kable()
```

### pp. 355, Eq. (10.8)
```{r}
fm_diff <- df %>% filter(year=="1982"|year=="1988") %>%
  plm(frate ~ beertax, data = ., index = c("state", "year"),
model = "fd")
coeftest(fm_diff) %>% tidy() %>% kable()
```

## p. 368, Table 10.1, numbers refer to cols.
```{r}
fm1 <- plm(frate ~ beertax, data = df, index = c("state", "year"), model = "pooling")
fm2 <- update(fm1, model = "within")
fm3 <- update(fm2, effect = "twoways")
fm4 <- update(fm3, . ~ . + drinkagec + punish + vmiles + unemp + log(income))
fm5 <- update(fm4, . ~ . - unemp - log(income))
fm6 <- update(fm4, . ~ . - drinkagec + drinkage)
```

```{r results='asis'}
ll<-list(fm1,fm2,fm3,fm4,fm5,fm6)
vcovHCC <- function(fm) {
  G <- length(unique(Fatalities$state))
  N <- length(Fatalities$state)
  dfa <-(G/(G - 1)) * (N - 1)/(fm$df.residual+G)
  return(dfa*vcovHC(fm, cluster="group", type="HC0"))
}  
selist <- ll %>% map(~coeftest(.,vcovHCC)[,2])
pvlist <- ll %>% map(~coeftest(.,vcovHCC)[,4])
selist[[1]] <- coeftest(fm1)[,2]
pvlist[[1]] <- coeftest(fm1)[,4]
htmlreg(ll, override.se=selist,override.pvalues=pvlist,omit.coef = "(Intercept)",
        reorder.coef = c(1:4,9,5:8),digits = 3)
```


